### PR TITLE
dotnetcore2.1

### PR DESCRIPTION
**Pull request by mkchx**
Created a new dotnetcore2.1 project and a new console app
Tested on a production env - docker debian container and it worked

### CODE REVIEW

**Comment by skrusty** [comment]
Nice, i will try and take a look shortly

**Comment by mkchx** [comment]
Yeah well it's not necessary to keep them both AspNetCore.AsterNET and AsterNET
can be made as single lib.
From technical side I had a problem with the connection on docker linux env
[themicster answer](https://github.com/AsterNET/AsterNET/issues/139) helped so I added the '\n' at ManagerReader ln:136 and the problem gone.
Now I haven't notice any other issue so far.

**Comment by Deantwo** [comment]
So, if you still have something you want to add to AsterNET, maybe you can make a new pull request that add it to Asterisk.NET?
A pull request with >3000 files changes is kinda insane.

**Comment by mkchx** [comment]
Well do you want me to upgrade Asterisk.NET to netcoreapp 2.1 instead of creating new library in the solution?

**Comment by skrusty** [comment]
Why are we not just adding a new project file targeting .net core, and linking to the original files. I am pretty sure there are no code changes required for 99% of the code base.

**Comment by Deantwo** [comment]
This >3000 file changes. Wouldn't it be easier to delete this pull request and the branch and start over?

**Comment by mkchx** [comment]
@Deantwo Ok, sorry for the mess

**Pull request closed without merging**
