### PR TITLE
Fix: Invalid Cast Exception #194

### PR DESCRIPTION
**Pull request by mech-dia**
Integrate new markers for new Asterisk versions.
Fix for issue #194

### CODE REVIEW

**Comment by Deantwo** [comment]
Do you have any idea in which Asterisk version this was changed?

**Comment by mech-dia** [comment]
No exception for Asterisk 13, but for Asterisk 16 we also have this exception. So it should be some version in between.

**Comment by Deantwo** [comment]
I was just wondering if this should be only for specific versions, or if it should really be an `OR` statement for both.

**Comment by mech-dia** [comment]
Sorry we can't test it for other versions.

**Pull request merged**
