### PR TITLE
Conf bridge events

### PR DESCRIPTION
**Pull request by moldypenguins**
See issue #63 confbridge list listrooms and their complete variants are missing in managerconnection
See issue #105 ConfBrifgeList correction proposal

### CODE REVIEW

**Comment by moldypenguins** [comment]
Must accept changes in pull request #175 Add references in summaries to asterisk docs (manager > events)

**Comment by moldypenguins** [comment]
See issue #105 ConfBrifgeList correction proposal 
See issue #63 confbridge list listrooms and their complete variants are missing in managerconnection

**Comment by Deantwo** [comment]
Why must #175 be merged first? The two are unrelated to each other.
Is #175 apart of this PR too? Why?

**Comment by moldypenguins** [comment]
I did this after the summaries so I started with the file that already had the summaries in it
I probably didn't have to though

**Comment by Deantwo** [comment]
Is that something you can correct? Wouldn't want conflicts if we can avoid it.

**Comment by moldypenguins** [comment]
i assume so, i'll post another pull request for it, or fix this one?

**Comment by Deantwo** [comment]
Which ever is the cleanest.

**Pull request closed without merging**
