### PR TITLE
This external IResponseHandler

### PR DESCRIPTION
**Pull request by ddyner**
This adds the possibility to handle asynchronous responses from an asterisk of external components

### CODE REVIEW

**Comment by skrusty** [comment]
I will try and review this today.

**Comment by skrusty** [comment]
Do you have an example of how you've used this?

**Comment by ddyner** [comment]
These changes were required to implement the operations async\await
Implemented the inheritor of the class ManagerConnection:
````
public class MyConnection : ManagerConnection
{
	public async Task<ManagerResponse> SendActionAsync(ManagerAction action)
	{
		var responseHandler = new TaskResponseHandler(action);
		ManagerConnection connection = null;

		base.SendAction(action, responseHandler);
		var task = responseHandler.TaskCompletionSource.Task;

		var result = await task
			.ContinueWith(x =>
				{
					RemoveResponseHandler(responseHandler);
					return x.Result;
				}
			)
			.ConfigureAwait(false);

		return result;
	}

	private class TaskResponseHandler : IResponseHandler
	{
		public TaskResponseHandler(ManagerAction action)
		{
			Action = action;
			TaskCompletionSource = new TaskCompletionSource<ManagerResponse>();
		}

		public TaskCompletionSource<ManagerResponse> TaskCompletionSource { get; }

		public ManagerAction Action { get; }

		public int Hash { get; set; }

		public void HandleResponse(ManagerResponse response)
		{
			TaskCompletionSource.TrySetResult(response);
		}

		public void Free() { }
	}
}
````

And the execution of an asynchronous operation is reduced to:
````
public class Test
    {
        public async Task<ManagerResponse> Ping()
        {
            var ping = new PingAction();
            var connection = new MyConnection();
            var result = await connection.SendActionAsync(ping);

            return result;
        }
    }
````

**Comment by skrusty** [comment]
Cool, maybe we could add that as another handler type available in the main library? 

Would you be willing to add that to the PR within Inline docs?

**Comment by skrusty** [comment]
(Called something like AsyncManagerConnection)

**Comment by ddyner** [comment]
Add SendActionAsync methods to ManagerConnection

**Comment by skrusty** [comment]
Please review build errors in Travis-CI

Manager/ManagerConnection.cs(104,62): error CS0246: The type or namespace name `MusicOnHoldEvent' could not be found. Are you missing an assembly reference?

**Comment by Deantwo** [comment]
@moldypenguins is attempting to do all this in #169.

**Pull request closed without merging**
