### PR TITLE
async/await

### PR DESCRIPTION
**Pull request by moldypenguins**
Update to pull request: This external IResponseHandler #84

### CODE REVIEW

**Comment by Deantwo** [comment]
So I can just close #84?

**Comment by moldypenguins** [comment]
I believe so. I think I got everything out of it.

**Comment by Deantwo** [comment]
Wish you would have done the summary additions/edits in another PR, it is a bit hard to see your other changes in this PR now.

**Comment by moldypenguins** [comment]
Yeah, I didn't mean to do it all in one
Let me try to revert it then re make the other changes

**Comment by Deantwo** [comment]
Not sure if reverting will fix it the ["Files changed"](https://github.com/AsterNET/AsterNET/pull/169/files) view, might have to just remake the whole PR. But give it a try.
Sorry I didn't notice this sooner, could have saved you some work that way, I have just been kinda busy.

**Pull request closed without merging**
