### PR TITLE
Get Option Return string

### PR DESCRIPTION
**Pull request by ShloimeRosenblum**
Change GetOption AGI command to return the result code as a string instead of char and fixes issue of not getting -1 on error

### CODE REVIEW

**Review by Deantwo — APPROVED** [review]
Looks like a simple change to me. Doesn't look like it would be a breaking change.

**Review by Deantwo — CHANGES_REQUESTED** [review]
Wait, the methods still return `char`, so I don't think this will compile.

**Comment by ShloimeRosenblum** [comment]
Updated

**Comment by Deantwo** [comment]
I don't know anything about AGI and I don't have the time to look at the code right now. Will need @skrusty to look at it probably.

But as far as I am reading, the methods aren't just returning a `char`, it is seemingly a "DTMF digit"?
> `/// <returns> the DTMF digit pressed or 0x0 if none was pressed.</returns>`

So, why are you trying to make it return a `string` instead?

**Comment by ShloimeRosenblum** [comment]
It is returning 0 if nothing is pressed and -1 on error https://wiki.asterisk.org/wiki/display/AST/Asterisk+19+AGICommand_stream+file
but -1 does not have an ascii representation code and it returns 0x0 on both
https://www.barcodefaq.com/ascii-chart-char-set/

**Comment by ShloimeRosenblum** [comment]
Ok i will revert this commit and fix the char result directly

**Comment by Deantwo** [comment]
> It is returning 0 if nothing is pressed and -1 on error https://wiki.asterisk.org/wiki/display/AST/Asterisk+19+AGICommand_stream+file but -1 does not have an ascii representation code and it returns 0x0 on both

Sounds like the actual API call is returning an `int` or `byte`, and the method is just returning it as a char to make it easier.

I would argue that if the API call returns `-1`, an error, the method should throw an exception instead.

**Comment by ShloimeRosenblum** [comment]
No this is the expected behavior in other functions and is not expected to throw exeption

**Comment by Deantwo** [comment]
> No this is the expected behavior in other functions and is not expected to throw exeption

Expected behavior for the raw API, yes.
But this is not the raw API, this is a .NET library. In .NET we throw exceptions when something like an expected error happens.

I confess that I don't know anything about AGI or how AsterNET's AGI code works, but it is definitely a better way of handling this issue.

**Comment by ShloimeRosenblum** [comment]
This is how it works across the library and changing this will not be consistent.
Please approve my other pull request which fixes the source of the issue and does not change the function return type

**Pull request closed without merging**
