### PR TITLE
async/await

### PR DESCRIPTION
**Pull request by moldypenguins**
New pull request for this change
changes SendAction(ManagerAction action, int timeOut) to SendAction(ManagerAction action, int timeout)

### CODE REVIEW

**Comment by skrusty** [comment]
can we get a demo/sample project put into the solution that uses the async methods? it helps in two ways, 1 demonstrate the usage, but also helps in testing.

**Comment by moldypenguins** [comment]
Good idea, I can do something for it this weekend

**Comment by Deantwo** [comment]
@skrusty, this pull request does not modify the same code #183, so I don't know if they will affect each other.

Does anyone know how this code works?

**Comment by skrusty** [comment]
@moldypenguins can you comment on if this conflicts/replaces pr #183 please

**Comment by moldypenguins** [comment]
> @moldypenguins can you comment on if this conflicts/replaces pr #183 please

it doesnt conflict or replace, maybe will help with sending so many actions at once though, it was a thought

**Comment by skrusty** [comment]
ok, so i think I am happy to approve this @Deantwo if everyone else is.

**Comment by moldypenguins** [comment]
As long as the lack of test case won't affect anything. I can add it in later, or maybe someone else can pick up where i've left off if its needed sooner

**Comment by Deantwo** [comment]
We are in an agreement that is an addition, right? It doesn't change any existing functionality?

**Comment by moldypenguins** [comment]
it does not

**Pull request merged**
