### PR TITLE
Some performance fixes

### PR DESCRIPTION
**Pull request by vait**
The first fix: when use this library under IIS poll you can catch memory leak - endless creation of threads without ending of stream read (nstream.EndRead(ar) never was called).
The second fix: the code that is waiting for the result will be executed in another thread

### CODE REVIEW

**Comment by Deantwo** [comment]
Interesting, will see if I can test the changes here during the week, if I have time.
Anyone else want to help?

**Comment by vait** [comment]
About TaskComplitionSource you can read here
https://hghltd.yandex.net/yandbtm?lang=en&fmode=inject&tm=1553546858&tld=ru&la=1553000448&text=https%3A%2F%2Fblogs.msdn.microsoft.com%2Fseteplia%2F2018%2F10%2F01%2Fthe-danger-of-taskcompletionsourcet-class%2F&url=https%3A%2F%2Fblogs.msdn.microsoft.com%2Fseteplia%2F2018%2F10%2F01%2Fthe-danger-of-taskcompletionsourcet-class%2F&l10n=ru&mime=html&sign=0e7bf69c27b87bf0f84ff03b87aed690&keyno=0
unfortunately the blog is unavailable now

What about creating thread, I can try to explain it )

**Comment by vait** [comment]
Hmmm... i look at our code one more time, and... may be the problem with thread abort exception was in our usage.

**Comment by Deantwo** [comment]
So was it an error on your end only?

**Comment by vait** [comment]
As for the commit b816bf - yes? it's error only my end. Sorry (
But 0e7c77b will improve performance of all project.
https://blogs.msdn.microsoft.com/seteplia/2018/10/01/the-danger-of-taskcompletionsourcet-class/ - now it works ))))

Maybe better if I'll create new PR with  only performance commit?

**Comment by Deantwo** [comment]
The simpler the PR, the easier it is to review and test it.

**Pull request closed without merging**
